"""empty message

Revision ID: bd5d70c477d5
Revises: 53ced4d24eae
Create Date: 2022-03-15 19:41:50.452148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5d70c477d5'
down_revision = '53ced4d24eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'completed')
    # ### end Alembic commands ###
