"""empty message

Revision ID: 0a31090ec49c
Revises: bd5d70c477d5
Create Date: 2022-03-15 19:49:10.898152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a31090ec49c'
down_revision = 'bd5d70c477d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('content', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'content')
    # ### end Alembic commands ###
