"""empty message

Revision ID: 9c233e509bd2
Revises: b510f0dc0755
Create Date: 2023-04-03 19:35:43.429258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c233e509bd2'
down_revision = 'b510f0dc0755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'channel_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channel_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
